name: Cache static files on AWS S3 storage

on:
  push:
    paths:
      - "**"

jobs:
  deploy:
    name: sync static sources from Github with AWS S3
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # aws user 연결
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_S3_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_S3_SECRET_KEY }}
          aws-region: ap-northeast-2

      # gatsby 빌드한 ./ s3로 업로드

      - name: sync static directory with s3
        run: aws s3 sync ./ s3://${{ secrets.AWS_S3_BUCKET_NAME }} --delete
      # 업로드한 s3 파일을 각 CDN 캐시 무효화하여 리프레시 하기
      - name: CloudFront Invalidation
        env:
          CLOUD_FRONT_ID: ${{ secrets.AWS_CLOUDFRONT_ID}}
        run: |
          aws cloudfront create-invalidation \
            --distribution-id $CLOUD_FRONT_ID --paths /*
